### ISSUE TITLE
[FEATURE ADDITION] Saving bios path...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#240]
Is it possible to add a feature to save the bios path ?

**Comment by Guillaumito** [comment]
I'm not sure to understand what you mean :)

**Comment by cyberwarriorx** [comment]
Do you mean something like this?
![mac bios preference](https://cloud.githubusercontent.com/assets/3471977/14943204/acee6760-0fa0-11e6-91e6-fb1612a00b1c.png)

**Comment by BenjaminSiskoo** [comment]
I explained the problem to Guillaume. I think he want to add it. Anyway, here the problem.

- Launch Yabause
- Select your bios.
- Now remove the path of the bios.
- Select the bios and you have to search in the folder again.
Yabause doesn't keep the position of the path. When you remove it, you're back on the exe folder and not in the bios folder.

Dunno it's more clear ^^

**Comment by cyberwarriorx** [comment]
Yeah I figured that was the issue. But what I'm trying to suggest is instead of clearing the bios path to use emulated bios, it stays as is and you have a check box that enables the emulated bios. Obviously if the bios path field is empty bios emulation is enabled by default and check box is grayed.

**Comment by BenjaminSiskoo** [comment]
Yeah I like that :) Good idea too

**Comment by cyberwarriorx** [comment]
Done :)

**Comment by BenjaminSiskoo** [comment]
Perfect, thanks :)
